### ISSUE TITLE
Error console gets spammed with CSS warnings.

### ISSUE THREAD

**Issue by cxd4** [bryc/mempak#10]
Guessing it's not really an "issue", in general.

Not sure how often this has been tested in those Mozilla-family-based browsers, but, based on the error console in one of those, I always get these six warnings every time I load the page via rawgit.com:
```
Warning: Unknown property '-moz-osx-font-smoothing'.  Declaration dropped.
Source File: http://rawgit.com/bryc/mempak/master/fonts/font-awesome.min.css
Line: 4, Column: 311
```
```
Warning: Expected 'none' or URL but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped.
Source File: http://rawgit.com/bryc/mempak/master/fonts/font-awesome.min.css
Line: 4, Column: 1454
```
```
Warning: Expected 'none' or URL but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped.
Source File: http://rawgit.com/bryc/mempak/master/fonts/font-awesome.min.css
Line: 4, Column: 1617
```
```
Warning: Expected 'none' or URL but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped.
Source File: http://rawgit.com/bryc/mempak/master/fonts/font-awesome.min.css
Line: 4, Column: 1783
```
```
Warning: Expected 'none' or URL but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped.
Source File: http://rawgit.com/bryc/mempak/master/fonts/font-awesome.min.css
Line: 4, Column: 1954
```
```
Warning: Expected 'none' or URL but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped.
Source File: http://rawgit.com/bryc/mempak/master/fonts/font-awesome.min.css
Line: 4, Column: 2127
```

**Comment by bryc** [comment]
Those seem to be CSS warnings, not JS warnings. I have those messages disabled in the console because they're _really_ common. Every webpage has 'em - it's when a CSS property is used that the browser doesn't understand. [Font Awesome](https://fortawesome.github.io/Font-Awesome/) uses a lot of cross-browser code to maximize browser support. The `progid` stuff is specific to IE for example.

It shouldn't cause any problems because the browser simply ignores it - that's why multiple vendor specific properties can be used, like `-o-x`, `-webkit-x` and `-moz-x`. Firefox will obviously not recognize the Opera or Webkit properties. To be honest I'm surprised there's only 6 of these.

**Comment by cxd4** [comment]
lol!  CSS warnings sorry, not JS.  Ate so much JS for breakfast and lunch I just said JS without even looking at the console actually.  (I did look at the code it highlighted, but it was all cramped together into a single line and I just tl;dr'd it as JS.)

Well I guess my OCD was hoping there would be a way to modify the CSS to prevent the warnings, but if it can't be done without either replacing Font Awesome entirely or using something different, then maybe the issue can't be helped.

**Comment by bryc** [comment]
Unfortunately not without potentially breaking IE or OS X things. Why not just disable CSS warnings?

I did modify the original font-awesome.min.css to remove WOFF2 fonts, because it was trying to load fonts that didn't exist (404 error), when I only had WOFF (original) fonts. I deleted all but the *.woff fonts from the package.

**Comment by cxd4** [comment]
I personally am not really a "disable warnings" kind of guy.  When it comes to clean performance/well-defined reactions, I always like to go straight for the source to maximize consistent, direct behavior.

However I understand it that there's nothing otherwise that can be done in this case without writing something in place of _Font Awesome_, so I ought to spare you the potential distraction and I think just close the issue.
