### ISSUE TITLE
Just a question about .note extension.

### ISSUE THREAD

**Issue by cxd4** [bryc/mempak#12]
No issue just wondering something, and not like I seem able to ask over IRC. :P 

Like 4 years ago when I began doing a mempak file system manager in C, I was wondering what extension to give note and page exports.  I thought I had chosen ".note" and ".page" file extensions, though looking back at my C sources from 3 years ago I guess I was wrong and just used `.bin` instead.  Instead, it appears your implementation is the one to use `.note` as the extension.

This just really weirds me out because I could have sworn I remembered finding some reason to use `.note`, or at least talking with somebody about it (may have been you), but it was too long ago to remember.

After all, `.bin` or maybe just using the 4-character extension code at index table node offsets header[0xC]..[0xF] would probably have worked just as well for the file extension?  Or was there something special about `.note`?

**Comment by bryc** [comment]
I originally used _**foo**_.note.bin, but switched to .note because it was shorter and more descriptive. The bin was just to specify it was binary...

I use _**foo**_.raw for the files saved without a header (by holding CTRL before saving).

The program doesn't care what extension you use when loading files, it just reads 36KB of any file and checks its validity. The chrome extension can allow for specific extension via dropdown, but it caused some problems, so it just adds ".note" to the text itself when prompting a save.

**Comment by cxd4** [comment]
Yeah .bin became my preference just as a technicality for no official, special extension being known, but I thought for sure I ended up choosing .note instead of .bin.

I think it's correct that the extension is ignored in your implementation.  Strictly speaking the controller pak dump files probably shouldn't need to have any file extension at all, so just initializing with the first 32KB or 36K is probably best.  (I'm not familiar with the 36-KB DexDrive variant or whatever that really is.)

Actually IIRC a part of the doc referred to the mempak "controller pak" accessory as the "controller RAM", so RAM probably made me think .bin extension for file exports.

>I use foo.raw for the files saved without a header (by holding CTRL before saving).

Oh wow, didn't find that it was possible to export the notes as header-less.

That's actually a very important feature I had to implement in my C mempak manager because of save-editing.  Like, if I export a _Quest 64_ note with your 32-byte header in it, it kind of just throws off the offsets for all the save-editing bits and makes it too annoying for my save editor to want to hack around.  So yeah header-less exports are an important feature.

Only problem is determining how to re-import them back into the mempak after save-editing. -.- I kinda used the filename itself to try to hold all the sufficient header info for re-importing raw note exports.  (Either that or I guess the only way would be to export a separate file alongside the .note to contain the 32-byte header.)

>Unfortunately I don't hang out on IRC anymore

Heh, well then it sounds like you've made a bit more progress in the dimension of life than I last did, so I can't say I'm disappointed.

**Comment by bryc** [comment]
I know this is kinda old but I am dusting off the code and looking into stuff now. 

> Only problem is determining how to re-import them back into the mempak after save-editing

Personally I would just open the .note in a hex editor and ignore the 32-byte header. It aligns nicely in a hex editor with 16 byte per row. Just add 0x20 to any offset etc. A good solution for this would be a feature where a note's data can be replaced from a raw file. It wouldn't be too difficult to add as long as the input data is the same size as the note data.

**Comment by cxd4** [comment]
Well there aren't issues with alignment, but you do want to be able to (re-)import a note (back) in.

Which is the problem I was referring to.  Anything e.g. a hex editor can be used to view the isolated note data, but it's not so much use to have the separate file available if it can't be touched and re-uploaded back to the mempak compatibly.  This is how the 32-byte header assists.

**Comment by bryc** [comment]
Hmm, 3 years later. Going to reopen this. A filename-based format is probably viable for re-inserting raw saves.

Raw files strip the 32-byte header. But only the **game code** and **starting index** are relevant for identifying an existing note in an MPK, which is fine for updating pre-existing data.

Consider a raw extracted note with the filename: **raw-NSME-7B.note**.

- **raw** specifies that it is a raw note file.
- **NSME** specifies the _gameCode_. In this case, the US version of SM64.
- **7B** (hex) specifies the _startIndex_, with a leading zero when necessary.

With that, the parser can check the NoteTable for an entry containing the two values, then prompt the user to overwrite if the file size matches (comparing size should be possible too).

The filename can be validated effectively with a regular expression, regardless of file extension: 

```js
/^(raw-N[0-9A-Z]{3}-[0-9A-F]{2}$)+/.test("raw-NSME-0F.note".slice(0,11));
```
- The combination of `raw-N` serve as a magic string of sorts, 5 fixed bytes.
- [A-Z]{3} restricts the _gameCode_ to three uppercase letters.
- The second "-" separator aids in parsing robustness, since it's a fixed byte.
- [0-9A-F]{2} restricts the _startIndex_ to two uppercase hex digits, enforcing a leading zero.

I considered using a 1-char modulo-62 [0-9A-Za-z] checksum, but honestly... its unlikely a filename with this pattern, that matches the size of the destination buffer, would end up getting imported by accident.

Also, since it only checks the first 11 characters, one can add identifiable text and it would work as expected, such as: **raw-NSME-0F-hacked_stats.note**.

Adding this to my todo

**Comment by bryc** [comment]
Added raw note import with commit e94d976.
